### ISSUE TITLE
请问支持pixel3吗？

### ISSUE THREAD

**Issue by y0an1** [MartinKayJr/KernelSU-Pixel3XL#1]
如题，请问大佬，这个支持pixel3吗？另外再请教下是哪个版本，谢谢！

**Comment by MartinKayJr** [comment]
pixel3和pixel3xl用的是同一个包，官方是这样写的

**Comment by MartinKayJr** [comment]
官方包你可以去Google的ROM包镜像下载

**Comment by y0an1** [comment]
> pixel3和pixel3xl用的是同一个包，官方是这样写的

好的大佬,谢谢了
